[package]
name = "runner"
version = "0.1.0"
description = "Runner - Web3 Jackpot Game"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "runner"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
custom-heap = []
custom-panic = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
sha3 = "0.10"

